server:
  port: 8085

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: backend-service
          uri: lb://backend-service
          predicates:
            - Path=/api/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka