spring:
  datasource:
    url: jdbc:postgresql://auth-db:5432/zonium_auth_db
    username: auth_user
    password: Zedd123321!
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 50

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka