spring:
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/zonium
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 50

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

logging:
  level:
    root: WARN
    org.ataraxii.wishlist: INFO

