spring:
  datasource:
    url: postgresql://api-db:5432/zonium_api_db
    username: api_user
    password: Zedd123321!
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 15
      idle-timeout: 60000
      minimum-idle: 2
      initialization-fail-timeout: -1

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka